### PR TITLE
Upgrade Python to 3.8

### PR DESCRIPTION
**Pull request by tomdyson**
to be consistent with wagtail-kit:

https://git.torchbox.com/internal/wagtail-kit/-/blob/master/wagtailkit_repo_name/Dockerfile#L19

Untested!

### CODE REVIEW

**Review by zerolab — APPROVED** [review]

**Review by zerolab — CHANGES_REQUESTED** [review]
Tested locally, with a Python 3.8 in the buster VM.
Needs `psycopg2-binary` to work

**Comment by tm-kn** [comment]
@zerolab Why `psycopg2-binary`? What for?

**Comment by zerolab** [comment]
@tm-kn no reason other than it being in my clipboard 🤦‍♂️

`psycopg2` is the recommended package for production use. Pushed to staging.

**Review by zerolab — APPROVED** [review]

**Comment by zerolab** [comment]
fixed via #100

**Pull request closed without merging**
