### PR TITLE
New services template [FE]

### PR DESCRIPTION
**Pull request by janehughes**
image

I couldn't see a way of building the new template without having the BE in place first (as there's no pattern lib), so I've created the new services template alongside the standard page template and added an if statement based on the page title for now.

### CODE REVIEW

**Comment by SharmaineLim** [comment]
Brian to:

1. Point the services page BE to the new services_page.html file.
2. Restore standard_page.html to its original state.

**Comment by BrianXu20** [comment]
@SharmaineLim no problem

**Comment by BrianXu20** [comment]
Pushing to https://github.com/wagtail/wagtail.io.git
remote: Permission to wagtail/wagtail.io.git denied to BrianXu20.

Apparently, I don’t have access on Wagtail.io so I can’t push, but once I got the access I will push my work immediately.

**Comment by BrianXu20** [comment]
- [Point the services page BE to the new services_page.html file.](https://github.com/wagtail/wagtail.io/pull/79)
- [Restore standard_page.html to its original state.](https://github.com/wagtail/wagtail.io/pull/78)

**Comment by tbrlpld** [comment]
I believe this on has been superseded by https://github.com/wagtail/wagtail.io/pull/95

**Pull request closed without merging**
